[package]
name = "rust-web-server"
version = "0.1.0"
authors = ["lyc101011 <lyc101011@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.4.5"
serde_derive = "1.0.32"
serde = "1.0.32"